CREATE TABLE IF NOT EXISTS sessions(
	id UUID UNIQUE NOT NULL DEFAULT GEN_RANDOM_UUID(),
  user_id UUID NOT NULL,
	agent VARCHAR(255) NOT NULL,
	PRIMARY KEY(id),
	CONSTRAINT fk_sessions_to_users FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);